[package]
name = "burnreport"
version = "0.2.0"
authors = ["Demonus <pogon.ap@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.69", features = ["derive"] }
serde_json = "1.0.22"
serde_derive = "1.0.69"
json = "*"

futures = "0.3.4"
bytes = "0.5.4"
log = "0.4.3"
env_logger = "0.7.0"

dotenv = "0.15.0"

csv = "1.1"

async-std = {version = "1", features = ["attributes"]}

sqlx = { version = "0.3", features = [ "macros", "sqlite", "chrono"] }

tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"